language: go
env:
  - GIMME_OS=linux GIMME_ARCH=amd64
#  - GIMME_OS=darwin GIMME_ARCH=amd64
#  - GIMME_OS=windows GIMME_ARCH=amd64
sudo: required
go:
  - 1.9
  - tip
install:
  - go get -d -v -t ./...
script:
  - export GOMAXPROCS=$(nproc) GOOS=$GIMME_OS GOARCH=$GIMME_ARCH
  # TODO test seems to fail on non linux platforms @ travis
  - go test -v -timeout=30s ./...
  - go build -o tg ./cli/cli.go
deploy:
  provider: releases
  api_key:
    secure: HKBkD8wKF3AboOl1AIJdNUl3m2xIt6IDOmNSXC5IBoEz4ZxJuGFO2ZKJIB3nyon5XZcu0T+I2krIVv+zXJTBSY+Ylb1GIYZv1gJwdcyQUOEQ9SIIpHuOjOe6W/PoMKlVlp8TVkv1/Qs51YL+YghI8Z78iPgVRm5RoXnwxBNSFwbf26N44VDWdXqs8hNWevpidn6cqCcEg0pFtcINYusOe9bH4VcJ3qlonaW2dEpe9iLh1wbY6HtbeDsuCOcrScAwGH7DDGXag9NttjKBeOp7dg66Myn00svcGzgppQSXpeHOGlE/EQDgiMMFFCYSf2wHvgB3i3w+PXz0sS7emJRTcjgzDPRqYJO392MLPKThT0yiXZ90u4Ie/QNe8Yn7c+f0cR56yBiGEwyIYH4bZNkDwAN3QMLSctJ/4zIhDO3xX9C/3hczKUlj74kZbzRiavfwI65korvigpqAg0eIRxgTaDsmFQZfLG29tfI/s6SsmPKG3njH5Nbznx6s2G136X3Q1WtUvC7THM4WfrB9+H1VPBwSE6hBP0cmbMC60v3wiqE1nMn0Eod9ooFycDVpbaS0XnFRAkTQHol19+jDNpaFnXHuyyXIEw1tzinO534H49fyXjDne/Dj3UfdONyduioCLT5nQz84sKhSr19iG6mdlu/oQ9ZPFeEguZVJBwMFBZI=
  file:
  - tg
  skip_cleanup: true
  on:
    tags: true
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
